package PLMS.server.panes;

import PLMS.Base.WidgetBase;
import PLMS.DataUnits.AFN04.F3;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.jidesoft.swing.JideLabel;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 */
public class setting_F3 extends SettingTab {
    private F3 f3;
    private JPanel panel1;
    private JTextField textField1;
    private JTextField 主站端口TextField;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;

    public setting_F3(F3 f3) {
        this.f3 = f3;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("setting_F3");
        frame.setContentPane(new setting_F3(null).getContentPane());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

   // @Override
    protected Object collectValues() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

   // @Override
    public Container getContentPane() {
        return panel1;  //To change body of implemented methods use File | Settings | File Templates.
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("right:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:p:noGrow,center:max(p;4px):noGrow,top:4dlu:noGrow,center:max(p;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JideLabel jideLabel1 = new JideLabel();
        jideLabel1.setText("主站IP");
        CellConstraints cc = new CellConstraints();
        panel1.add(jideLabel1, cc.xy(1, 1, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JideLabel jideLabel2 = new JideLabel();
        jideLabel2.setText("主站备用IP");
        panel1.add(jideLabel2, cc.xy(1, 3));
        textField1 = new JTextField();
        panel1.add(textField1, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel3 = new JideLabel();
        jideLabel3.setHorizontalAlignment(2);
        jideLabel3.setHorizontalTextPosition(2);
        jideLabel3.setText("主站端口");
        panel1.add(jideLabel3, cc.xy(1, 2, CellConstraints.RIGHT, CellConstraints.CENTER));
        主站端口TextField = new JTextField();
        panel1.add(主站端口TextField, cc.xy(3, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField3 = new JTextField();
        panel1.add(textField3, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel4 = new JideLabel();
        jideLabel4.setText("主站备用端口IP");
        panel1.add(jideLabel4, cc.xy(1, 5));
        textField4 = new JTextField();
        panel1.add(textField4, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel5 = new JideLabel();
        jideLabel5.setText("网关IP");
        panel1.add(jideLabel5, cc.xy(1, 7));
        final JideLabel jideLabel6 = new JideLabel();
        jideLabel6.setText("网关端口");
        panel1.add(jideLabel6, cc.xy(1, 9));
        textField5 = new JTextField();
        panel1.add(textField5, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField6 = new JTextField();
        panel1.add(textField6, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel7 = new JideLabel();
        jideLabel7.setText("代理IP");
        panel1.add(jideLabel7, cc.xy(1, 11));
        textField7 = new JTextField();
        panel1.add(textField7, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel8 = new JideLabel();
        jideLabel8.setText("代理端口");
        panel1.add(jideLabel8, cc.xy(1, 13));
        textField8 = new JTextField();
        panel1.add(textField8, cc.xy(3, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel9 = new JideLabel();
        jideLabel9.setText("APN");
        panel1.add(jideLabel9, cc.xy(1, 15));
        textField9 = new JTextField();
        panel1.add(textField9, cc.xy(3, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        jideLabel3.setLabelFor(主站端口TextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
