package PLMS.server.panes;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.jidesoft.swing.JideLabel;

import javax.swing.*;

/**
 * Created by IntelliJ IDEA.
 * User: Administrator
 * Date: 12-2-20
 * Time: 下午7:12
 * To change this template use File | Settings | File Templates.
 */
public class setting_F4 {
    private JPanel panel1;
    private JTextField textField1;
    private JTextField textField3;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JideLabel jideLabel1 = new JideLabel();
        jideLabel1.setText("主站电话号码");
        CellConstraints cc = new CellConstraints();
        panel1.add(jideLabel1, cc.xy(1, 1));
        textField1 = new JTextField();
        panel1.add(textField1, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField3 = new JTextField();
        panel1.add(textField3, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JideLabel jideLabel2 = new JideLabel();
        jideLabel2.setText("短信中心号码");
        panel1.add(jideLabel2, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
