package PLMS.server.panes;

import PLMS.Base.WidgetBase;
import PLMS.DataUnits.AFN04.F10;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 */
public class setting_F10 extends WidgetBase {

    private F10 fnData;
    private JPanel panel1;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;
    private JTextField textField10;

    public setting_F10(F10 fn) {
        this.fnData = fn;
    }

    @Override
    protected Object collectValues() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public Container getContentPane() {
        return panel1;  //To change body of implemented methods use File | Settings | File Templates.
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        textField1 = new JTextField();
        CellConstraints cc = new CellConstraints();
        panel1.add(textField1, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("电能表（采样设备）序号");
        panel1.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("所属测量点号");
        panel1.add(label2, cc.xy(1, 4));
        textField2 = new JTextField();
        panel1.add(textField2, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("通信速率");
        panel1.add(label3, cc.xy(1, 7));
        final JLabel label4 = new JLabel();
        label4.setText("通信规约类型");
        panel1.add(label4, cc.xy(1, 15));
        final JLabel label5 = new JLabel();
        label5.setText("通信端口");
        panel1.add(label5, cc.xy(1, 11));
        textField3 = new JTextField();
        panel1.add(textField3, cc.xy(1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField4 = new JTextField();
        panel1.add(textField4, cc.xy(1, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField5 = new JTextField();
        panel1.add(textField5, cc.xy(1, 16, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label6 = new JLabel();
        label6.setText("通信地址");
        panel1.add(label6, cc.xy(1, 18));
        final JLabel label7 = new JLabel();
        label7.setText("通信密码");
        panel1.add(label7, cc.xy(1, 22));
        final JLabel label8 = new JLabel();
        label8.setText("电能费率");
        panel1.add(label8, cc.xy(1, 27));
        textField6 = new JTextField();
        panel1.add(textField6, cc.xy(1, 20, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField7 = new JTextField();
        panel1.add(textField7, cc.xy(1, 24, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField8 = new JTextField();
        panel1.add(textField8, cc.xy(1, 29, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label9 = new JLabel();
        label9.setText("有功电能示值整数位个数");
        panel1.add(label9, cc.xy(1, 31));
        final JLabel label10 = new JLabel();
        label10.setText("小数位个数");
        panel1.add(label10, cc.xy(1, 36));
        textField9 = new JTextField();
        panel1.add(textField9, cc.xy(1, 33, CellConstraints.FILL, CellConstraints.DEFAULT));
        textField10 = new JTextField();
        panel1.add(textField10, cc.xy(1, 38, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
